name = "MechanicalUnits"
uuid = "e6be9192-89dc-11e9-36e6-5dbcb28f419e"
authors = ["hustf <hustf@users.noreply.github.com>"]
version = "0.5.6"

[deps]
Unitfu = "5ee08b94-2369-4f4a-b8c7-99333ba35fb0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "1.4.0"
